x-common-settings: &common-settings
  restart: always
  networks:
      - foxogram
  build:
    context: ./foxogram-api

services:
  foxogram-api:
    <<: *common-settings
    container_name: foxogram-api
    image: foxogram/api:prod
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-api.rule: Host(`api.foxogram.su`)
      traefik.http.routers.foxogram-api.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-api.loadbalancer.server.port: 8080
      traefik.http.routers.foxogram-api.middlewares: ratelimit@file

  foxogram-api-dev:
    <<: *common-settings
    container_name: foxogram-api-dev
    image: foxogram/api:dev
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-api-dev.rule: Host(`api.dev.foxogram.su`)
      traefik.http.routers.foxogram-api-dev.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-api-dev.loadbalancer.server.port: 8080
      traefik.http.routers.foxogram-api-dev.middlewares: ratelimit@file

networks:
  foxogram:
    external: true
