spring:
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: foxogram
    password: passwd
    url: jdbc:postgresql://localhost:5432/foxogram
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    org.springframework: INFO

springdoc:
  swagger-ui:
    enabled: false

smtp:
  host: smtp.mailersend.net
  port: 587
  username: user
  password: pass
  email: noreply@foxogram.su

minio:
  url: https://min.io # minio api url
  name: # access key
  secret: # secret key

jwt:
  secret: # random secret key

api:
  version: 1
  env: dev # dev or prod
  url: http://localhost:8080
  cdn:
    url: https://cdn.foxogram.su
  gateway:
    production_url: wss://gateway.foxogram.su
    development_url: wss://gateway.dev.foxogram.su
  app:
    production_url: https://app.foxogram.su
    development_url: https://app.dev.foxogram.su
