spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: foxogram
    password: passwd
    url: jdbc:postgresql://localhost:5432/foxogram
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: localhost

rabbit:
  queue: events

springdoc:
  swagger-ui:
    enabled: false

smtp:
  host: smtp.mailersend.net
  port: 587
  username: user
  password: pass
  email: noreply@foxogram.su

minio:
  url: https://min.io # minio api url
  name: # access key
  secret: # secret key

jwt:
  secret: # random secret key

api:
  version: 1
  env: dev # dev or prod
